### ISSUE TITLE
[CHANGE] Add a column for file hierarchy level

### ISSUE THREAD

**Issue by dla-kramski** [dla-marbach/filedriller#15]
A column in the output file for the (relative) hierarchy level of each file/directory recorded seems useful.

**Comment by dla-fritz** [comment]
As the level can be determined from separators, i.e. "/", the information is not lost. However, can you give a use case where this information could be useful, @dla-kramski ?

**Comment by dla-kramski** [comment]
Yes, the level can be determined from the number of separators. But an explicit, numeric level would be much easier to filter when you have to look through large lists - be it via autofilter in Excel or Calc, or on the command line. Also, there may be quoted separators as part of filenames, especially in exotic filesystems. Overall, a numeric level would be much easier to evaluate.

**Comment by steffenfritz** [comment]
As it is not the file hierarchy level but the depth from the input directory I would call the column "LevelFromInput" or "DepthFromInput".

Ok?
