### ISSUE TITLE
[CHANGE] Add more basic technical metadata

### ISSUE THREAD

**Issue by dla-kramski** [dla-marbach/filedriller#16]
For a appropriate, complete file listing the output should contain columns for

- Permissions
- UserID
- GroupID
- ModDate
- ModTime
- StatusChgDate
- StatusChgTime
- AccessDate
- AccessTime

**Comment by steffenfritz** [comment]
That is a difficult task for most of the metadata, esp. permissions and userIDs/groupIDs. 

As filedriller works on the file level, you can pass every file level source like external mounts or local storage to it. In some cases the operating system takes care of permissions and user- or groupIDs, in some not. Ext stores IDs in the inode, the mapping to a name is done with /etc/passwd and /etc/groups. Some FAT implementations store the information at byte offset 0x12, some not.

While it might be possible to get numerical values from unix-like filesystems, other filesystems don't have such information or could even return misleading information.

**Comment by steffenfritz** [comment]
Times added in #20
