### ISSUE TITLE
[CHANGE] Add a column for basic file type

### ISSUE THREAD

**Issue by dla-kramski** [dla-marbach/filedriller#17]
Can we have a column for the basic file type in analogy to the "find" command? ("f" for files, "d" for directories etc.)

**Comment by dla-fritz** [comment]
To be more precise:

```
             b       block special
             c       character special
             d       directory
             f       regular file
             l       symbolic link
             p       FIFO
             s       socket
```

**Comment by steffenfritz** [comment]
I added "gnuFindType" as registry value and "d" so far as value for it, e.g. 

    test/subtest,,gnuFindType,d,,,,,,,2fada7ef-791e-4d9e-860b-421803c352c3,,

However, there is no "gnuFindType" for files. If it is a file the registry is "pronom". 

So I think a column just for the type would be highly redundant (while also be explicit and I like explicit but...)

Ok?
