### ISSUE TITLE
[CHANGE] Implement as a new option: LastModificationDate (mtime)

### ISSUE THREAD

**Issue by steph-nb** [dla-marbach/filedriller#20]
(Copy of codeberg.org issue nr. 5)

Hi Steffen,

when experimenting with problematic hd-images containing identical files at several distinct paths - which I can easily detect already by sorting by hash-value, what is great already (!) - I thought that as an additional output-option the mtime of the files would be great.
We then could easily detect the oldest copy of identical files, and only treat that specific copy.

What do you think, could you implement mtime in a next version?

Many thanks and BR,
Stephan

**Comment by steffenfritz** [comment]
Added it by using https://github.com/djherbis/times Please check supported times here https://github.com/djherbis/times#supported-times  

It is btw not an option, all dates are added to the output when available. If not the column is empty.
