### ISSUE TITLE
[BUG] csv-output incorrect, when directoryname/path contains the csv-separator

### ISSUE THREAD

**Issue by steph-nb** [dla-marbach/filedriller#22]
**Describe the bug**
Directorynames/paths get splitted up in several csv-fields, when they contain a comma.
E.g.: "OCRA, OCRB, MICR"

**To Reproduce**
1. Let filedriller analyze a folderstructure containing such a name
2. the output csv will contain a line/lies with cutted directorynames and too many data fields

**Expected behavior**
the csv should be written in a correct way.
E.g. by using "" around the filename

**Comment by steffenfritz** [comment]
Thanks! Fixed with next commit.
